"""Update email field

Revision ID: 965702cffcff
Revises: 312623b8599b
Create Date: 2023-08-03 19:46:44.286700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965702cffcff'
down_revision = '312623b8599b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
